2018-09-02 07:04:20,612 ERROR: Exception on /index [GET] [in c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Peggy Li\projects\bytehacks-2018\app\routes.py", line 27, in index
    return render_template('index.html', title='Home', posts=posts)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Peggy Li\projects\bytehacks-2018\app\templates\index.html", line 13, in template
    {% if text.sentiment is not None %}
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\environment.py", line 543, in _generate
    optimized=self.optimized)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\compiler.py", line 82, in generate
    generator.visit(node)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\compiler.py", line 799, in visit_Template
    self.blockvisit(block.body, block_frame)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\compiler.py", line 378, in blockvisit
    self.visit(node, frame)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\compiler.py", line 1172, in visit_If
    self.blockvisit(node.else_, if_frame)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\compiler.py", line 378, in blockvisit
    self.visit(node, frame)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\compiler.py", line 1122, in visit_For
    self.blockvisit(node.body, loop_frame)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\compiler.py", line 378, in blockvisit
    self.visit(node, frame)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\compiler.py", line 1157, in visit_If
    self.visit(node.test, if_frame)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\compiler.py", line 70, in new_func
    return f(self, node, frame, **kwargs)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\compiler.py", line 1497, in visitor
    self.visit(node.node, frame)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\compiler.py", line 70, in new_func
    return f(self, node, frame, **kwargs)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\compiler.py", line 1607, in visit_Test
    self.fail('no test named %r' % node.name, node.lineno)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\compiler.py", line 315, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: no test named 'None'
2018-09-02 07:05:26,699 INFO: Myapp startup [in C:\Users\Peggy Li\projects\bytehacks-2018\app\__init__.py:40]
2018-09-02 07:05:32,739 ERROR: Exception on /index [GET] [in c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Peggy Li\projects\bytehacks-2018\app\routes.py", line 27, in index
    return render_template('index.html', title='Home', posts=posts)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Peggy Li\projects\bytehacks-2018\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Peggy Li\projects\bytehacks-2018\app\templates\base.html", line 37, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Peggy Li\projects\bytehacks-2018\app\templates\index.html", line 15, in block "content"
    {% if text.sentiment > 0 %}
TypeError: '>' not supported between instances of 'str' and 'int'
2018-09-02 07:07:19,742 INFO: Myapp startup [in C:\Users\Peggy Li\projects\bytehacks-2018\app\__init__.py:40]
